# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!
target 'RxSiwft' do
    pod 'RxSwift'
    pod 'RxCocoa'
end

target 'RxSiwftTests' do

end

target 'RxSiwftUITests' do

end

